#!/bin/sh
### BEGIN INIT INFO
# Provides:          website
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Boot Personal Website on Startup
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions
. /home/pi/projects/website/.envrc

case "$1" in
  start)
    log_begin_msg "Starting Personal Website"
    sleep 60 # database needs to boot also
    cd /home/pi/projects/website && ./website-server.exe &
    log_end_msg $?
    exit 0
    ;;
  stop)
    log_begin_msg "Stopping Personal Website"
    ps | kill $(grep -Po "(?<=^ )([0-9]+)(?=.*website-server.exe)")
    log_end_msg $?
    exit 0
    ;;
  *)
    echo "Usage: /etc/init.d/website {start|stop}"
    exit 1
    ;;
esac